# Generated by Django 4.1.7 on 2023-03-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=52)),
                ('Continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], max_length=13)),
                ('Region', models.CharField(max_length=26)),
                ('SurfaceArea', models.FloatField(default=0.0)),
                ('IndepYear', models.SmallIntegerField(null=True)),
                ('Population', models.IntegerField(default=0)),
                ('LifeExpectancy', models.FloatField(null=True)),
                ('GNP', models.FloatField(null=True)),
                ('GNPOld', models.FloatField(null=True)),
                ('LocalName', models.CharField(max_length=45)),
                ('GovernmentForm', models.CharField(max_length=45)),
                ('HeadOfState', models.CharField(max_length=60, null=True)),
                ('Capital', models.IntegerField(null=True)),
                ('Code2', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('CountryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('Language', models.CharField(default='', max_length=30)),
                ('IsOfficial', models.CharField(max_length=3)),
                ('Percentage', models.FloatField(default=0.0)),
                
            ],
            options={
                'db_table': 'countrylanguage',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=35)),
                ('CountryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('District', models.CharField(default='', max_length=20)),
                ('Population', models.IntegerField(default=0)),
                
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
